source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'PNImagePickerViewController_Example' do
  pod 'PNImagePickerViewController', :path => '../'
  pod 'PureLayout'
end

target 'PNImagePickerViewController_Tests' do
  pod 'PNImagePickerViewController', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
end
